version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
      - dependency-name: "puma"
        versions: "<6.0.0"
