version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
    allow:
      - dependency-name: "puma"
        versions: ">= 6.0.0"
