version: 1
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
      - dependency-name: "puma"
        versions: "<6.0.0"
