on:
  push:
    branches:
      - main

jobs:
  update-yarn-lock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.13.0'

      - name: Install Yarn
        run: npm install -g yarn@1.22.5

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Commit and push changes
        run: |
          git config --global user.name "oc-2"
          git config --global user.email "185859974+oc-2@users.noreply.github.com"
          git add .
          git commit -m "Update yarn.lock" --allow-empty
          git push origin HEAD:main